from github_client.models.main import GitHubUser, RateLimitResponse, Repository
import json

user = json.loads('''{
  "login": "aijurist",
  "id": 114634067,
  "node_id": "U_kgDOBtUtUw",
  "avatar_url": "https://avatars.githubusercontent.com/u/114634067?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/aijurist",
  "html_url": "https://github.com/aijurist",
  "followers_url": "https://api.github.com/users/aijurist/followers",
  "following_url": "https://api.github.com/users/aijurist/following{/other_user}",
  "gists_url": "https://api.github.com/users/aijurist/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/aijurist/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/aijurist/subscriptions",
  "organizations_url": "https://api.github.com/users/aijurist/orgs",
  "repos_url": "https://api.github.com/users/aijurist/repos",
  "events_url": "https://api.github.com/users/aijurist/events{/privacy}",
  "received_events_url": "https://api.github.com/users/aijurist/received_events",
  "type": "User",
  "user_view_type": "public",
  "site_admin": false,
  "name": "Shan0103",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 31,
  "public_gists": 0,
  "followers": 0,
  "following": 1,
  "created_at": "2022-09-29T02:30:18Z",
  "updated_at": "2025-02-21T03:29:32Z"
}''')

print("Github Users:", GitHubUser(**user))

repo = json.loads('''{
  "id": 675868875,
  "node_id": "R_kgDOKEjwyw",
  "name": "aijurist",
  "full_name": "aijurist/aijurist",
  "private": false,
  "owner": {
    "login": "aijurist",
    "id": 114634067,
    "node_id": "U_kgDOBtUtUw",
    "avatar_url": "https://avatars.githubusercontent.com/u/114634067?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aijurist",
    "html_url": "https://github.com/aijurist",
    "followers_url": "https://api.github.com/users/aijurist/followers",
    "following_url": "https://api.github.com/users/aijurist/following{/other_user}",
    "gists_url": "https://api.github.com/users/aijurist/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aijurist/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aijurist/subscriptions",
    "organizations_url": "https://api.github.com/users/aijurist/orgs",
    "repos_url": "https://api.github.com/users/aijurist/repos",
    "events_url": "https://api.github.com/users/aijurist/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aijurist/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "html_url": "https://github.com/aijurist/aijurist",
  "description": "A landing page for my webapp",
  "fork": false,
  "url": "https://api.github.com/repos/aijurist/aijurist",
  "forks_url": "https://api.github.com/repos/aijurist/aijurist/forks",
  "keys_url": "https://api.github.com/repos/aijurist/aijurist/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/aijurist/aijurist/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/aijurist/aijurist/teams",
  "hooks_url": "https://api.github.com/repos/aijurist/aijurist/hooks",
  "issue_events_url": "https://api.github.com/repos/aijurist/aijurist/issues/events{/number}",
  "events_url": "https://api.github.com/repos/aijurist/aijurist/events",
  "assignees_url": "https://api.github.com/repos/aijurist/aijurist/assignees{/user}",
  "branches_url": "https://api.github.com/repos/aijurist/aijurist/branches{/branch}",
  "tags_url": "https://api.github.com/repos/aijurist/aijurist/tags",
  "blobs_url": "https://api.github.com/repos/aijurist/aijurist/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/aijurist/aijurist/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/aijurist/aijurist/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/aijurist/aijurist/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/aijurist/aijurist/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/aijurist/aijurist/languages",
  "stargazers_url": "https://api.github.com/repos/aijurist/aijurist/stargazers",
  "contributors_url": "https://api.github.com/repos/aijurist/aijurist/contributors",
  "subscribers_url": "https://api.github.com/repos/aijurist/aijurist/subscribers",
  "subscription_url": "https://api.github.com/repos/aijurist/aijurist/subscription",
  "commits_url": "https://api.github.com/repos/aijurist/aijurist/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/aijurist/aijurist/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/aijurist/aijurist/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/aijurist/aijurist/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/aijurist/aijurist/contents/{+path}",
  "compare_url": "https://api.github.com/repos/aijurist/aijurist/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/aijurist/aijurist/merges",
  "archive_url": "https://api.github.com/repos/aijurist/aijurist/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/aijurist/aijurist/downloads",
  "issues_url": "https://api.github.com/repos/aijurist/aijurist/issues{/number}",
  "pulls_url": "https://api.github.com/repos/aijurist/aijurist/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/aijurist/aijurist/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/aijurist/aijurist/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/aijurist/aijurist/labels{/name}",
  "releases_url": "https://api.github.com/repos/aijurist/aijurist/releases{/id}",
  "deployments_url": "https://api.github.com/repos/aijurist/aijurist/deployments",
  "created_at": "2023-08-07T23:29:32Z",
  "updated_at": "2024-08-27T14:45:46Z",
  "pushed_at": "2024-08-27T14:45:42Z",
  "git_url": "git://github.com/aijurist/aijurist.git",
  "ssh_url": "git@github.com:aijurist/aijurist.git",
  "clone_url": "https://github.com/aijurist/aijurist.git",
  "svn_url": "https://github.com/aijurist/aijurist",
  "homepage": null,
  "size": 10407,
  "stargazers_count": 0,
  "watchers_count": 0,
  "language": "HTML",
  "has_issues": true,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": true,
  "has_discussions": false,
  "forks_count": 0,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 0,
  "license": null,
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [

  ],
  "visibility": "public",
  "forks": 0,
  "open_issues": 0,
  "watchers": 0,
  "default_branch": "master",
  "temp_clone_token": null,
  "network_count": 0,
  "subscribers_count": 1
}''')

print("Repository: ", Repository(**repo))
